# Generated by Django 5.1 on 2024-09-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='unit_price',
        ),
    ]
