# Generated by Django 5.1 on 2024-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'manager'), (2, 'customer')], default=2, null=True),
        ),
    ]
